### ISSUE TITLE
Remove interval with specific ID

### ISSUE THREAD

**Issue by grovesNL** [TyberiusPrime/nested_intervals#2]
Hi 👋 thank you for this crate!

I'm looking at crates that might fit my use case where I sometimes introduce temporary intervals, so I was wondering if it might be possible to be able to remove an interval by ID. If it's not currently possible, is there anything about this data structure that might make it difficult?

**Comment by TyberiusPrime** [comment]
Well, the data structure is essentially an array of  nested trees (as fast as I remember, it's been as while), plus an array of ids. I'd imagine you could go and prune it accordingly.

But since there is no id to range lookup implemented, it's going to be at least O(n) for scanning, and worse for rearranging the array after deletions. Plus messing with the tree.

Depending on your exact use case, one could imagine either some kind of tombstone system, or keeping a Hashset with Ids to filter on output/match.
 
Or perhaps paying the hashset check costs up front, just recreating the data structure minus  the ranges you don't need anymore might be appropriate... Depends on your filter to query ratio I suppose.

Or maybe having the IDs be Refcell<Option<i32>> similar that you can turn into None from the outside. I seem to remember the data structure being generic. But maybe that was just over the range type.

Best of luck!

**Comment by grovesNL** [comment]
Thanks for the suggestions! I'll check it out and see if I could track ID<->tree node cleanly somehow.
